var myWindowId;

// Get message strings from locale-specific messages.json file
let getMessage = browser.i18n.getMessage;
let pageInfoTitle        = getMessage("pageInfoTitle");
let pageTitle            = getMessage("pageTitle");
let pageUrl              = getMessage("pageUrl");
let structureTitle       = getMessage("structureTitle");
let tabIsLoading         = getMessage("tabIsLoading");
let protocolNotSupported = getMessage("protocolNotSupported");

/*
*   When the sidebar loads, store the ID of the current window and update
*   the sidebar content.
*/
browser.windows.getCurrent({ populate: true }).then( (windowInfo) => {
  myWindowId = windowInfo.id;
  updateContent();
});

/*
*   Handle window focus change events by checking whether the sidebar is
*   open in the newly focused window, and if so, save the new window ID
*   and update the sidebar content.
*/
browser.windows.onFocusChanged.addListener((windowId) => {
  console.log(`windowId: ${windowId}`);
  function onInvalidId (error) {
    // console.log(`onInvalidId: ${error}`);
  }

  function onGotStatus (result) {
    if (result) {
      myWindowId = windowId;
      updateContent();
      console.log('Updating for onFocusChanged to window: ' + myWindowId);
    }
  }

  let checkingOpenStatus = browser.sidebarAction.isOpen({ windowId });
  checkingOpenStatus.then(onGotStatus, onInvalidId);
});

/*
*   getFormattedData: Convert the contentInfo data into an HTML string with
*   internationalized labels.
*/
function getFormattedData (info) {
  return `<h3>${pageTitle}</h3>
          <p>${info.title}</p>
          <h3>${pageUrl}</h3>
          <p>${info.url}</p>`;
}

function formatStructureInfo (infoList) {
  let html = '';
  for (let i = 0; i < infoList.length; i++) {
    let name = infoList[i].name, text = infoList[i].text;
    console.log(`${name}: ${text}`);
    html += `<${name}><span style="color: #999">${name}: </span>${text}</${name}>`;
    // html += `<${name} title="${name}">${text}</${name}>`;
  }
  return html;
}

/*
*   Display the content generated by the content script.
*/
function updateSidebar (info) {
  let pageInfo  = document.getElementById('page-info-content');
  let structure = document.getElementById('structure-content');

  // page-info and structure titles
  document.getElementById('page-info-title').textContent = pageInfoTitle;
  document.getElementById('structure-title').textContent = structureTitle;

  // page-info and structure content
  if (typeof info === 'object') {
    pageInfo.innerHTML = getFormattedData(info);
    structure.innerHTML = formatStructureInfo(info.infoList);
  }
  else {
    pageInfo.textContent = info;
    structure.textContent = '';
  }
}

/*
*   Generic error handler
*/
function onError (error) {
  console.log(`Error: ${error}`);
}

/*
*   Handle tabs.onUpdated event only when status is 'complete':
*   There can be numerous calls to this event handler, as multiple
*   events are triggered while the tab is loading the page.
*/
let timeoutID;
function handleTabUpdate (tabId, changeInfo, tab) {
  // Skip content update when new page is loaded in background tab
  if (!tab.active) return;

  clearTimeout(timeoutID);
  if (changeInfo.status === "complete") {
    updateContent();
  }
  else {
    timeoutID = setTimeout(function () {
      updateSidebar(tabIsLoading);
    }, 250);
  }
}

/*
*   Update sidebar content by running the content script and then
*   referencing the contentInfo variable in the background script.
*/
function updateContent () {

  function onGotPage (page) {
    updateSidebar(page.contentInfo);
  }

  function onExecuted (result) {
    let gettingPage = browser.runtime.getBackgroundPage();
    gettingPage.then(onGotPage, onError);
  }

  browser.tabs.query({ windowId: myWindowId, active: true })
  .then((tabs) => {
    let tab = tabs[0];
    if (tab.url.indexOf('http:') != 0 && tab.url.indexOf('https:') != 0) {
      updateSidebar (protocolNotSupported);
    }
    else {
      let executing = browser.tabs.executeScript({
        file: '../content.js'
      });
      executing.then(onExecuted, onError);
    }
  });
}

/*
*   Update variable in background script used for toggling sidebar
*/
function updateOpenStatus (isOpen) {
  function onGotPage (page) {
    page.sidebarIsOpen = isOpen;
    console.log(`open status: ${isOpen}`);
  }

  let gettingPage = browser.runtime.getBackgroundPage();
  gettingPage.then(onGotPage, onError);
}

/*
*   Load and unload event listeners and keep track of sidebar status
*/
window.addEventListener("load",   function (e) {
  updateOpenStatus(true);
  browser.tabs.onUpdated.addListener(handleTabUpdate, { properties: ["status"] });
  browser.tabs.onActivated.addListener(updateContent);
});

window.addEventListener("unload", function (e) {
  updateOpenStatus(false);
  browser.tabs.onUpdated.removeListener(handleTabUpdate);
  browser.tabs.onActivated.removeListener(updateContent);
});
